### ISSUE TITLE
Update Caricoos logo

### ISSUE THREAD

**Issue by kknee** [asascience-open/maracoos_assets#14]
@cgalvarino just emailed the file to you

**Comment by cgalvarino** [comment]
Isn't it already up there? May need to refresh.

[image1.PNG]

On Oct 11, 2015, at 6:30 AM, Kelly Knee <notifications@github.com<mailto:notifications@github.com>> wrote:

@cgalvarinohttps://github.com/cgalvarino just emailed the file to you

##

**Comment by kknee** [comment]
yep....still working on that first cup of coffee, sorry
