### ISSUE TITLE
Add AmSeas source to Caricoos

### ISSUE THREAD

**Issue by kknee** [asascience-open/maracoos_assets#15]
on hold until we have new endpoints from EDS team

**Comment by kknee** [comment]
@cgalvarino is this called something other than Amseas...I think you said you added it, but I don't see it.

**Comment by kknee** [comment]
Apparently, I'm just going to keep answering my own questions this morning.  Guessing this is the NCOM source, which is down.  Sigh...will follow up with EDS team.

**Comment by kknee** [comment]
Okay...so the source name has changed.  Caricoos is hitting NCOM_AM_SEA, and should be hitting NCOM_AM_SEAS.  @cgalvarino can you update?

**Comment by cgalvarino** [comment]
OK, wxflow.  ZING.  I'll get it tomorrow.

**Comment by cgalvarino** [comment]
While I was in there I noticed that a layer slotted for Gliders (NCOM SST (S Atlantic)) wasn't part of the Cari suite.  It needs to be updated to SEAS, too.  But its legend isn't working.

no work (NCOM SST (S Atlantic))
http://coastmap.com/ecop/wms.aspx?LAYERS=NCOM_AM_SEAS_SST&FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=SST_USCG-25-30&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&TIME=&SRS=EPSG%3A3857&LAYER=NCOM_AM_SEAS_SST

work (ROMS water temp (Carib))
http://coastmap.com/ecop/wms.aspx?LAYERS=CARIB_ROMSR1_SST&FORMAT=image%2Fpng&TRANSPARENT=TRUE&STYLES=SST_USCG-25-30&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetLegendGraphic&TIME=&SRS=EPSG%3A3857&LAYER=CARIB_ROMSR1_SST

Should NCOM SST be taken offline completely?

**Comment by kknee** [comment]
not yet, Ben was trying to get that up to EDS production tonight.  I guess it got pushed until tomorrow.

**Comment by cgalvarino** [comment]
I updated everything to AM_SEAS in #23 and I added NCOM SST to the cari TOC.  If I need to roll NCOM SST back, let me know.  If not, and everything looks good, please close this one out.

**Comment by kknee** [comment]
@cgalvarino NCOM_AM_SEAS_SST is operational and working in the EDS viewer, but choking in the caricoos assets map.  can you take a look?

**Comment by cgalvarino** [comment]
It didn't like the STYLE I'm passing.  I change it to WATER_TEMP-25-30 in the next PR.
