### ISSUE TITLE
Update WF endpoints

### ISSUE THREAD

**Issue by kknee** [asascience-open/maracoos_assets#18]
From WF: 

The server where the sos service has changed.  Please change www.weatherflow.com to d.weatherflow.com.  For example

http://d.weatherflow.com/sos/sos.pl?request=GetObservation&service=SOS&version=1.0.0&offering=urn:x-weatherflow:def:station:weatherflow.com::1127&procedure=urn:x-weatherflow:def:station:weatherflow.com::1127&observedproperty=Winds&responseFormat=text/xml;schema=%22ioos/0.6.1

**Comment by kknee** [comment]
Interesting, GitHub changed the word 'station' into an icon.

**Comment by kknee** [comment]
note - this one applies to Caricoos and Maricoos.

**Comment by cgalvarino** [comment]
No, their endpoint hasn't changed.  It looks like something critical in the reqeust and/or response has.

**Comment by cgalvarino** [comment]
They need to update their getcaps.  Although the getcaps itself is available at d.weatherflow.com, they are pointing to the old one in their getcaps.

```
    <ows:Operation name="GetObservation">
      <ows:DCP>
        <ows:HTTP>
          <ows:Get xlink:href="http://www.weatherflow.com/sos.pl"/>
        </ows:HTTP>
      </ows:DCP>
      <ows:Parameter name="observedProperty">
        <ows:AllowedValues>
          <ows:Value>watertemperature</ows:Value>
          <ows:Value>winds</ows:Value>
        </ows:AllowedValues>
      </ows:Parameter>
    </ows:Operation>
```

**Comment by kknee** [comment]
notified WF, will let you know when it's fixed.

**Comment by kknee** [comment]
@cgalvarino should be all set

**Comment by cgalvarino** [comment]
I agree.  I didn't have to touch anything.  wxflow showing up @ assets.
