### ISSUE TITLE
Update Assets Map IOOS Logo on 10/21

### ISSUE THREAD

**Issue by kknee** [asascience-open/maracoos_assets#27]
Right after IOOS reveal at MTS.

**Comment by cgalvarino** [comment]
Can you attach the logo to this issue?

**Comment by kknee** [comment]
Nope, it's under lock and key until next week. This is just a reminder for us to update the assets map when it comes out.

**Comment by cgalvarino** [comment]
Look how Johnny on the spot I am.

![image](https://cloud.githubusercontent.com/assets/180985/10636814/1fc414e2-77d0-11e5-9a54-03fa547f287d.png)

**Comment by kknee** [comment]
Will send the logo as soon as I get to computer.

Sent from my iPhone

On Oct 21, 2015, at 8:46 AM, Charlton Galvarino <notifications@github.com<mailto:notifications@github.com>> wrote:

Look how Johnny on the spot I am.

[image]https://cloud.githubusercontent.com/assets/180985/10636814/1fc414e2-77d0-11e5-9a54-03fa547f287d.png

—
Reply to this email directly or view it on GitHubhttps://github.com/asascience-open/maracoos_assets/issues/27#issuecomment-149883950.

This e-mail message and any attached file is the property of the sender and is sent in confidence to the addressee only.
Internet communications are not secure and RPS is not responsible for their abuse by third parties, any alteration or corruption in transmission or for any loss or damage caused by a virus or by other means.

Any advice contained in this e-mail is for information purposes only.

RPS Group Plc, company number: 208 7786 (England). Registered office: 20 Western Avenue Milton Park Abingdon Oxfordshire OX14 4SH.
RPS Group Plc web link: http://www.rpsgroup.com

**Comment by cgalvarino** [comment]
#28
